version: '3.8'
networks:
  gv-network:
    driver: bridge

volumes:
  prometheus_data:
    driver: local

services:
  postgres:
    container_name: gestao_vagas_postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_vagas

  sonarqube:
    container_name: sonarqube
    image: sonarqube:9.9.0-community
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - gv-network
    ports:
      - "9090:9090"